name: Test Workflow
on: 
  push: # enabling push event on master branch to fire the workflow
    branches: 
    - main

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout current code using public action
        uses: actions/checkout@v2
      - name: get the list of files in our current directory and its sub directory
        run: |
          pwd
          ls -alR

  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: print current files
        run: |
          pwd
          ls -alR

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: print env variables
        run: echo $VAR1 $VAR2 $VAR3
        env:
          VAR1: Hi
          VAR2: Hello
          VAR3: Hey
